apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: rg-dev-app
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: eastus
---
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: app-keyvault-24214
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: eastus
  owner:
    name: rg-dev-app
    kind: ResourceGroup
  properties:
    tenantId: b41b72d0-4e9f-4c26-8a69-f949f367c91d
    sku:
      family: "A"
      name: "standard"
    accessPolicies:
      - tenantId: b41b72d0-4e9f-4c26-8a69-f949f367c91d
        objectId: 0e853340-9172-4350-9408-b68508021edb  # User or Service Principal Object ID
        permissions:
          secrets:
            - get
            - list
            - set
    enableSoftDelete: true
